"""Stage 2: Claude reviews and enhances low-confidence content from Ollama."""

import json
import logging

from anthropic import AsyncAnthropic

from app.models.profile import Profile

logger = logging.getLogger(__name__)

CONFIDENCE_THRESHOLD = 0.8


def _build_enhancement_prompt(draft: dict, profile: Profile) -> str:
    hi = profile.home_identity
    h = profile.household
    tone = profile.output_tone.tone
    home_type = (hi.home_type or "home").replace("_", " ")

    household_notes = []
    if h.num_children > 0:
        household_notes.append(f"{h.num_children} children in household")
    if h.has_pets:
        household_notes.append(f"pets: {h.pet_types or 'unspecified'}")
    if h.has_elderly:
        household_notes.append("elderly household members")
    if h.has_allergies:
        household_notes.append("allergies/sensitivities")

    context = f"Home: {home_type}, {hi.owner_renter}. "
    if household_notes:
        context += "Household: " + ", ".join(household_notes) + ". "
    context += f"Tone: {tone}."

    return f"""Review and enhance the following draft binder content. The content was generated by a local LLM with confidence scores.

CONTEXT: {context}

DRAFT CONTENT:
{json.dumps(draft, indent=2)}

INSTRUCTIONS:
1. For items with confidence >= {CONFIDENCE_THRESHOLD}: keep as-is unless there's a factual or safety issue.
2. For items with confidence < {CONFIDENCE_THRESHOLD}: rewrite with better reasoning and accuracy.
3. For ALL items: check for safety gaps (e.g., if children are present, add child-safety notes where relevant).
4. Ensure tone consistency ({tone}).
5. Set confidence to 1.0 for all enhanced items.

OUTPUT FORMAT (strict JSON, same structure as input):
{{
  "intros": {{
    "section_1": {{"text": "...", "confidence": 1.0}},
    ...
  }},
  "gaps": {{
    ...
  }}
}}

Output ONLY valid JSON. No markdown fences or extra text."""


class ClaudeEnhancer:
    """Stage 2: Claude reviews and enhances low-confidence content."""

    def __init__(self, api_key: str):
        self.client = AsyncAnthropic(api_key=api_key)

    async def enhance(self, draft: dict, profile: Profile) -> dict:
        # Check if anything needs enhancement
        needs_work = False
        for category in ["intros", "gaps"]:
            for item in draft.get(category, {}).values():
                if item.get("confidence", 0) < CONFIDENCE_THRESHOLD:
                    needs_work = True
                    break

        if not needs_work:
            logger.info("All draft content is high-confidence, skipping Claude enhancement")
            return draft

        prompt = _build_enhancement_prompt(draft, profile)

        try:
            message = await self.client.messages.create(
                model="claude-sonnet-4-20250514",
                max_tokens=4096,
                messages=[{"role": "user", "content": prompt}],
            )
            raw = message.content[0].text
            return json.loads(raw)
        except (json.JSONDecodeError, KeyError) as e:
            logger.warning("Claude returned invalid JSON: %s", e)
            return draft
        except Exception as e:
            logger.warning("Claude enhancement failed: %s", e)
            return draft
