"""Tests for JWT hardening: iss/aud claims, validation, and SSO readiness.

Covers: tokens with correct claims pass, tokens with wrong issuer/audience
        are rejected, existing endpoints validate claims properly.
"""

import pytest
from datetime import datetime, timedelta
from unittest.mock import AsyncMock

from jose import jwt

from app.config import settings
from app.tests.conftest import make_access_token, make_refresh_token


# ---------------------------------------------------------------------------
# Access token claim validation
# ---------------------------------------------------------------------------

@pytest.mark.asyncio
async def test_access_token_includes_iss_aud_iat(client, mock_db):
    """Access tokens generated by the system include iss, aud, and iat claims."""
    token = make_access_token()
    payload = jwt.decode(
        token, settings.jwt_secret,
        algorithms=[settings.jwt_algorithm],
        audience=settings.jwt_audience,
    )

    assert payload["iss"] == settings.jwt_issuer
    assert payload["aud"] == settings.jwt_audience
    assert "iat" in payload


@pytest.mark.asyncio
async def test_refresh_token_includes_iss_aud_iat(client, mock_db):
    """Refresh tokens include iss, aud, and iat claims."""
    token = make_refresh_token()
    payload = jwt.decode(
        token, settings.jwt_secret,
        algorithms=[settings.jwt_algorithm],
        audience=settings.jwt_audience,
    )

    assert payload["iss"] == settings.jwt_issuer
    assert payload["aud"] == settings.jwt_audience
    assert "iat" in payload


@pytest.mark.asyncio
async def test_valid_token_with_correct_claims_passes(client, mock_db):
    """Token with correct iss/aud is accepted by protected endpoints."""
    token = make_access_token()
    mock_db.profiles.find_one = AsyncMock(return_value=None)

    resp = await client.get(
        "/api/profile/",
        headers={"Authorization": f"Bearer {token}"},
    )

    # Profile not found is expected (404), but NOT 401
    assert resp.status_code in (200, 404)


@pytest.mark.asyncio
async def test_token_with_wrong_issuer_rejected(client, mock_db):
    """Token signed with wrong issuer is rejected."""
    now = datetime.utcnow()
    bad_token = jwt.encode(
        {
            "sub": "aabbccddeeff001122334455",
            "email": "test@example.com",
            "is_admin": False,
            "iss": "wrong-issuer",
            "aud": settings.jwt_audience,
            "iat": now,
            "exp": now + timedelta(minutes=15),
        },
        settings.jwt_secret,
        algorithm=settings.jwt_algorithm,
    )

    resp = await client.get(
        "/api/profile/",
        headers={"Authorization": f"Bearer {bad_token}"},
    )

    assert resp.status_code == 401


@pytest.mark.asyncio
async def test_token_with_wrong_audience_rejected(client, mock_db):
    """Token signed with wrong audience is rejected."""
    now = datetime.utcnow()
    bad_token = jwt.encode(
        {
            "sub": "aabbccddeeff001122334455",
            "email": "test@example.com",
            "is_admin": False,
            "iss": settings.jwt_issuer,
            "aud": "wrong-audience",
            "iat": now,
            "exp": now + timedelta(minutes=15),
        },
        settings.jwt_secret,
        algorithm=settings.jwt_algorithm,
    )

    resp = await client.get(
        "/api/profile/",
        headers={"Authorization": f"Bearer {bad_token}"},
    )

    assert resp.status_code == 401


@pytest.mark.asyncio
async def test_token_without_iss_aud_rejected(client, mock_db):
    """Legacy token without iss/aud claims is rejected (migration safety)."""
    now = datetime.utcnow()
    legacy_token = jwt.encode(
        {
            "sub": "aabbccddeeff001122334455",
            "email": "test@example.com",
            "is_admin": False,
            "exp": now + timedelta(minutes=15),
        },
        settings.jwt_secret,
        algorithm=settings.jwt_algorithm,
    )

    resp = await client.get(
        "/api/profile/",
        headers={"Authorization": f"Bearer {legacy_token}"},
    )

    assert resp.status_code == 401


# ---------------------------------------------------------------------------
# Refresh flow with iss/aud
# ---------------------------------------------------------------------------

@pytest.mark.asyncio
async def test_refresh_with_correct_claims_succeeds(client, mock_db):
    """Refresh token with correct iss/aud rotates successfully."""
    from bson import ObjectId

    user_id = "aabbccddeeff001122334455"
    jti = "jti-test-iss-aud"
    token = make_refresh_token(user_id=user_id, jti=jti)

    mock_db.refresh_tokens.find_one = AsyncMock(return_value={
        "_id": ObjectId(), "jti": jti, "user_id": user_id,
    })
    mock_db.users.find_one = AsyncMock(return_value={
        "_id": ObjectId(user_id), "email": "test@example.com", "is_admin": False,
    })
    mock_db.refresh_tokens.delete_one = AsyncMock()
    mock_db.refresh_tokens.insert_one = AsyncMock()

    resp = await client.post(
        "/api/auth/refresh",
        cookies={"refresh_token": token},
    )

    assert resp.status_code == 200
    assert "access_token" in resp.json()


@pytest.mark.asyncio
async def test_refresh_with_wrong_audience_rejected(client, mock_db):
    """Refresh token with wrong audience is rejected."""
    now = datetime.utcnow()
    bad_refresh = jwt.encode(
        {
            "sub": "aabbccddeeff001122334455",
            "type": "refresh",
            "jti": "jti-bad-aud",
            "iss": settings.jwt_issuer,
            "aud": "not-binderpro",
            "iat": now,
            "exp": now + timedelta(days=7),
        },
        settings.jwt_secret,
        algorithm=settings.jwt_algorithm,
    )

    resp = await client.post(
        "/api/auth/refresh",
        cookies={"refresh_token": bad_refresh},
    )

    assert resp.status_code == 401
